export enum SortedByFieldEnum {
  _id = '_id',
  age = 'age',
  name = 'name',
  surname = 'surname',
  email = 'email',
  phone = 'phone',
  course = 'course',
  course_format = 'course_format',
  course_type = 'course_type',
  status = 'status',
  sum = 'sum',
  alreadyPaid = 'alreadyPaid',
  created_at = 'created_at',
}
